/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Person extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4456526445129855832L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"firstname\",\"type\":\"string\"},{\"name\":\"lastname\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"county\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"},{\"name\":\"homePhone\",\"type\":\"string\"},{\"name\":\"cellPhone\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"website\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Person> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Person> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Person> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Person> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Person> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Person to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Person from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Person instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Person fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence firstname;
  private java.lang.CharSequence lastname;
  private java.lang.CharSequence company;
  private java.lang.CharSequence street;
  private java.lang.CharSequence city;
  private java.lang.CharSequence county;
  private java.lang.CharSequence state;
  private java.lang.CharSequence zip;
  private java.lang.CharSequence homePhone;
  private java.lang.CharSequence cellPhone;
  private java.lang.CharSequence email;
  private java.lang.CharSequence website;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Person() {}

  /**
   * All-args constructor.
   * @param firstname The new value for firstname
   * @param lastname The new value for lastname
   * @param company The new value for company
   * @param street The new value for street
   * @param city The new value for city
   * @param county The new value for county
   * @param state The new value for state
   * @param zip The new value for zip
   * @param homePhone The new value for homePhone
   * @param cellPhone The new value for cellPhone
   * @param email The new value for email
   * @param website The new value for website
   */
  public Person(java.lang.CharSequence firstname, java.lang.CharSequence lastname, java.lang.CharSequence company, java.lang.CharSequence street, java.lang.CharSequence city, java.lang.CharSequence county, java.lang.CharSequence state, java.lang.CharSequence zip, java.lang.CharSequence homePhone, java.lang.CharSequence cellPhone, java.lang.CharSequence email, java.lang.CharSequence website) {
    this.firstname = firstname;
    this.lastname = lastname;
    this.company = company;
    this.street = street;
    this.city = city;
    this.county = county;
    this.state = state;
    this.zip = zip;
    this.homePhone = homePhone;
    this.cellPhone = cellPhone;
    this.email = email;
    this.website = website;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return firstname;
    case 1: return lastname;
    case 2: return company;
    case 3: return street;
    case 4: return city;
    case 5: return county;
    case 6: return state;
    case 7: return zip;
    case 8: return homePhone;
    case 9: return cellPhone;
    case 10: return email;
    case 11: return website;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: firstname = (java.lang.CharSequence)value$; break;
    case 1: lastname = (java.lang.CharSequence)value$; break;
    case 2: company = (java.lang.CharSequence)value$; break;
    case 3: street = (java.lang.CharSequence)value$; break;
    case 4: city = (java.lang.CharSequence)value$; break;
    case 5: county = (java.lang.CharSequence)value$; break;
    case 6: state = (java.lang.CharSequence)value$; break;
    case 7: zip = (java.lang.CharSequence)value$; break;
    case 8: homePhone = (java.lang.CharSequence)value$; break;
    case 9: cellPhone = (java.lang.CharSequence)value$; break;
    case 10: email = (java.lang.CharSequence)value$; break;
    case 11: website = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'firstname' field.
   * @return The value of the 'firstname' field.
   */
  public java.lang.CharSequence getFirstname() {
    return firstname;
  }


  /**
   * Sets the value of the 'firstname' field.
   * @param value the value to set.
   */
  public void setFirstname(java.lang.CharSequence value) {
    this.firstname = value;
  }

  /**
   * Gets the value of the 'lastname' field.
   * @return The value of the 'lastname' field.
   */
  public java.lang.CharSequence getLastname() {
    return lastname;
  }


  /**
   * Sets the value of the 'lastname' field.
   * @param value the value to set.
   */
  public void setLastname(java.lang.CharSequence value) {
    this.lastname = value;
  }

  /**
   * Gets the value of the 'company' field.
   * @return The value of the 'company' field.
   */
  public java.lang.CharSequence getCompany() {
    return company;
  }


  /**
   * Sets the value of the 'company' field.
   * @param value the value to set.
   */
  public void setCompany(java.lang.CharSequence value) {
    this.company = value;
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }


  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'county' field.
   * @return The value of the 'county' field.
   */
  public java.lang.CharSequence getCounty() {
    return county;
  }


  /**
   * Sets the value of the 'county' field.
   * @param value the value to set.
   */
  public void setCounty(java.lang.CharSequence value) {
    this.county = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'zip' field.
   * @return The value of the 'zip' field.
   */
  public java.lang.CharSequence getZip() {
    return zip;
  }


  /**
   * Sets the value of the 'zip' field.
   * @param value the value to set.
   */
  public void setZip(java.lang.CharSequence value) {
    this.zip = value;
  }

  /**
   * Gets the value of the 'homePhone' field.
   * @return The value of the 'homePhone' field.
   */
  public java.lang.CharSequence getHomePhone() {
    return homePhone;
  }


  /**
   * Sets the value of the 'homePhone' field.
   * @param value the value to set.
   */
  public void setHomePhone(java.lang.CharSequence value) {
    this.homePhone = value;
  }

  /**
   * Gets the value of the 'cellPhone' field.
   * @return The value of the 'cellPhone' field.
   */
  public java.lang.CharSequence getCellPhone() {
    return cellPhone;
  }


  /**
   * Sets the value of the 'cellPhone' field.
   * @param value the value to set.
   */
  public void setCellPhone(java.lang.CharSequence value) {
    this.cellPhone = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'website' field.
   * @return The value of the 'website' field.
   */
  public java.lang.CharSequence getWebsite() {
    return website;
  }


  /**
   * Sets the value of the 'website' field.
   * @param value the value to set.
   */
  public void setWebsite(java.lang.CharSequence value) {
    this.website = value;
  }

  /**
   * Creates a new Person RecordBuilder.
   * @return A new Person RecordBuilder
   */
  public static Person.Builder newBuilder() {
    return new Person.Builder();
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Person RecordBuilder
   */
  public static Person.Builder newBuilder(Person.Builder other) {
    if (other == null) {
      return new Person.Builder();
    } else {
      return new Person.Builder(other);
    }
  }

  /**
   * Creates a new Person RecordBuilder by copying an existing Person instance.
   * @param other The existing instance to copy.
   * @return A new Person RecordBuilder
   */
  public static Person.Builder newBuilder(Person other) {
    if (other == null) {
      return new Person.Builder();
    } else {
      return new Person.Builder(other);
    }
  }

  /**
   * RecordBuilder for Person instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Person>
    implements org.apache.avro.data.RecordBuilder<Person> {

    private java.lang.CharSequence firstname;
    private java.lang.CharSequence lastname;
    private java.lang.CharSequence company;
    private java.lang.CharSequence street;
    private java.lang.CharSequence city;
    private java.lang.CharSequence county;
    private java.lang.CharSequence state;
    private java.lang.CharSequence zip;
    private java.lang.CharSequence homePhone;
    private java.lang.CharSequence cellPhone;
    private java.lang.CharSequence email;
    private java.lang.CharSequence website;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Person.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.firstname)) {
        this.firstname = data().deepCopy(fields()[0].schema(), other.firstname);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lastname)) {
        this.lastname = data().deepCopy(fields()[1].schema(), other.lastname);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.company)) {
        this.company = data().deepCopy(fields()[2].schema(), other.company);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.street)) {
        this.street = data().deepCopy(fields()[3].schema(), other.street);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.city)) {
        this.city = data().deepCopy(fields()[4].schema(), other.city);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.county)) {
        this.county = data().deepCopy(fields()[5].schema(), other.county);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.state)) {
        this.state = data().deepCopy(fields()[6].schema(), other.state);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.zip)) {
        this.zip = data().deepCopy(fields()[7].schema(), other.zip);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.homePhone)) {
        this.homePhone = data().deepCopy(fields()[8].schema(), other.homePhone);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.cellPhone)) {
        this.cellPhone = data().deepCopy(fields()[9].schema(), other.cellPhone);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.email)) {
        this.email = data().deepCopy(fields()[10].schema(), other.email);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.website)) {
        this.website = data().deepCopy(fields()[11].schema(), other.website);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing Person instance
     * @param other The existing instance to copy.
     */
    private Builder(Person other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.firstname)) {
        this.firstname = data().deepCopy(fields()[0].schema(), other.firstname);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastname)) {
        this.lastname = data().deepCopy(fields()[1].schema(), other.lastname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.company)) {
        this.company = data().deepCopy(fields()[2].schema(), other.company);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.street)) {
        this.street = data().deepCopy(fields()[3].schema(), other.street);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.city)) {
        this.city = data().deepCopy(fields()[4].schema(), other.city);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.county)) {
        this.county = data().deepCopy(fields()[5].schema(), other.county);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.state)) {
        this.state = data().deepCopy(fields()[6].schema(), other.state);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.zip)) {
        this.zip = data().deepCopy(fields()[7].schema(), other.zip);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.homePhone)) {
        this.homePhone = data().deepCopy(fields()[8].schema(), other.homePhone);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.cellPhone)) {
        this.cellPhone = data().deepCopy(fields()[9].schema(), other.cellPhone);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.email)) {
        this.email = data().deepCopy(fields()[10].schema(), other.email);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.website)) {
        this.website = data().deepCopy(fields()[11].schema(), other.website);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'firstname' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstname() {
      return firstname;
    }


    /**
      * Sets the value of the 'firstname' field.
      * @param value The value of 'firstname'.
      * @return This builder.
      */
    public Person.Builder setFirstname(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.firstname = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'firstname' field has been set.
      * @return True if the 'firstname' field has been set, false otherwise.
      */
    public boolean hasFirstname() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'firstname' field.
      * @return This builder.
      */
    public Person.Builder clearFirstname() {
      firstname = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastname' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastname() {
      return lastname;
    }


    /**
      * Sets the value of the 'lastname' field.
      * @param value The value of 'lastname'.
      * @return This builder.
      */
    public Person.Builder setLastname(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.lastname = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastname' field has been set.
      * @return True if the 'lastname' field has been set, false otherwise.
      */
    public boolean hasLastname() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastname' field.
      * @return This builder.
      */
    public Person.Builder clearLastname() {
      lastname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'company' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompany() {
      return company;
    }


    /**
      * Sets the value of the 'company' field.
      * @param value The value of 'company'.
      * @return This builder.
      */
    public Person.Builder setCompany(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.company = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'company' field has been set.
      * @return True if the 'company' field has been set, false otherwise.
      */
    public boolean hasCompany() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'company' field.
      * @return This builder.
      */
    public Person.Builder clearCompany() {
      company = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }


    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public Person.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.street = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public Person.Builder clearStreet() {
      street = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public Person.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.city = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public Person.Builder clearCity() {
      city = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'county' field.
      * @return The value.
      */
    public java.lang.CharSequence getCounty() {
      return county;
    }


    /**
      * Sets the value of the 'county' field.
      * @param value The value of 'county'.
      * @return This builder.
      */
    public Person.Builder setCounty(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.county = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'county' field has been set.
      * @return True if the 'county' field has been set, false otherwise.
      */
    public boolean hasCounty() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'county' field.
      * @return This builder.
      */
    public Person.Builder clearCounty() {
      county = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public Person.Builder setState(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.state = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public Person.Builder clearState() {
      state = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'zip' field.
      * @return The value.
      */
    public java.lang.CharSequence getZip() {
      return zip;
    }


    /**
      * Sets the value of the 'zip' field.
      * @param value The value of 'zip'.
      * @return This builder.
      */
    public Person.Builder setZip(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.zip = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'zip' field has been set.
      * @return True if the 'zip' field has been set, false otherwise.
      */
    public boolean hasZip() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'zip' field.
      * @return This builder.
      */
    public Person.Builder clearZip() {
      zip = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'homePhone' field.
      * @return The value.
      */
    public java.lang.CharSequence getHomePhone() {
      return homePhone;
    }


    /**
      * Sets the value of the 'homePhone' field.
      * @param value The value of 'homePhone'.
      * @return This builder.
      */
    public Person.Builder setHomePhone(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.homePhone = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'homePhone' field has been set.
      * @return True if the 'homePhone' field has been set, false otherwise.
      */
    public boolean hasHomePhone() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'homePhone' field.
      * @return This builder.
      */
    public Person.Builder clearHomePhone() {
      homePhone = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'cellPhone' field.
      * @return The value.
      */
    public java.lang.CharSequence getCellPhone() {
      return cellPhone;
    }


    /**
      * Sets the value of the 'cellPhone' field.
      * @param value The value of 'cellPhone'.
      * @return This builder.
      */
    public Person.Builder setCellPhone(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.cellPhone = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'cellPhone' field has been set.
      * @return True if the 'cellPhone' field has been set, false otherwise.
      */
    public boolean hasCellPhone() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'cellPhone' field.
      * @return This builder.
      */
    public Person.Builder clearCellPhone() {
      cellPhone = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public Person.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.email = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public Person.Builder clearEmail() {
      email = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'website' field.
      * @return The value.
      */
    public java.lang.CharSequence getWebsite() {
      return website;
    }


    /**
      * Sets the value of the 'website' field.
      * @param value The value of 'website'.
      * @return This builder.
      */
    public Person.Builder setWebsite(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.website = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'website' field has been set.
      * @return True if the 'website' field has been set, false otherwise.
      */
    public boolean hasWebsite() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'website' field.
      * @return This builder.
      */
    public Person.Builder clearWebsite() {
      website = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Person build() {
      try {
        Person record = new Person();
        record.firstname = fieldSetFlags()[0] ? this.firstname : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastname = fieldSetFlags()[1] ? this.lastname : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.company = fieldSetFlags()[2] ? this.company : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.street = fieldSetFlags()[3] ? this.street : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.city = fieldSetFlags()[4] ? this.city : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.county = fieldSetFlags()[5] ? this.county : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.state = fieldSetFlags()[6] ? this.state : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.zip = fieldSetFlags()[7] ? this.zip : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.homePhone = fieldSetFlags()[8] ? this.homePhone : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.cellPhone = fieldSetFlags()[9] ? this.cellPhone : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.email = fieldSetFlags()[10] ? this.email : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.website = fieldSetFlags()[11] ? this.website : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Person>
    WRITER$ = (org.apache.avro.io.DatumWriter<Person>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Person>
    READER$ = (org.apache.avro.io.DatumReader<Person>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.firstname);

    out.writeString(this.lastname);

    out.writeString(this.company);

    out.writeString(this.street);

    out.writeString(this.city);

    out.writeString(this.county);

    out.writeString(this.state);

    out.writeString(this.zip);

    out.writeString(this.homePhone);

    out.writeString(this.cellPhone);

    out.writeString(this.email);

    out.writeString(this.website);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.firstname = in.readString(this.firstname instanceof Utf8 ? (Utf8)this.firstname : null);

      this.lastname = in.readString(this.lastname instanceof Utf8 ? (Utf8)this.lastname : null);

      this.company = in.readString(this.company instanceof Utf8 ? (Utf8)this.company : null);

      this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);

      this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);

      this.county = in.readString(this.county instanceof Utf8 ? (Utf8)this.county : null);

      this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);

      this.zip = in.readString(this.zip instanceof Utf8 ? (Utf8)this.zip : null);

      this.homePhone = in.readString(this.homePhone instanceof Utf8 ? (Utf8)this.homePhone : null);

      this.cellPhone = in.readString(this.cellPhone instanceof Utf8 ? (Utf8)this.cellPhone : null);

      this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);

      this.website = in.readString(this.website instanceof Utf8 ? (Utf8)this.website : null);

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.firstname = in.readString(this.firstname instanceof Utf8 ? (Utf8)this.firstname : null);
          break;

        case 1:
          this.lastname = in.readString(this.lastname instanceof Utf8 ? (Utf8)this.lastname : null);
          break;

        case 2:
          this.company = in.readString(this.company instanceof Utf8 ? (Utf8)this.company : null);
          break;

        case 3:
          this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);
          break;

        case 4:
          this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          break;

        case 5:
          this.county = in.readString(this.county instanceof Utf8 ? (Utf8)this.county : null);
          break;

        case 6:
          this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          break;

        case 7:
          this.zip = in.readString(this.zip instanceof Utf8 ? (Utf8)this.zip : null);
          break;

        case 8:
          this.homePhone = in.readString(this.homePhone instanceof Utf8 ? (Utf8)this.homePhone : null);
          break;

        case 9:
          this.cellPhone = in.readString(this.cellPhone instanceof Utf8 ? (Utf8)this.cellPhone : null);
          break;

        case 10:
          this.email = in.readString(this.email instanceof Utf8 ? (Utf8)this.email : null);
          break;

        case 11:
          this.website = in.readString(this.website instanceof Utf8 ? (Utf8)this.website : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










